### ISSUE TITLE
[BUG] No Vault Name - Empty String

### ISSUE THREAD

**Issue by ultimatehecker** [polypixeldev/polypass#23]
**Describe the bug**
I don't know if this is exactly a bug or an intended feature, but you are able to create a vault without a name

**To Reproduce**
1. Create a vault
2. Edit the h.ppv.json
3. Change the vault name
4. relogin

**Expected behavior**
The JSON file should have some read-only implication on it

**Screenshots**
![image](https://user-images.githubusercontent.com/86735991/233653790-931f4259-73d6-4a12-ae4a-afee65ba3524.png)

**Desktop (if applicable):**
 - OS: Windows 10
 - Version: 1.0.0

**Additional context**
This kinda merges with the feature to be able to change the vault name, but it should be impossible to create a vault with an empty string, since you can't make a vault without a name in the UI itself

**Comment by polypixeldev** [comment]
That's out of the control of the app, you can't really stop people from manually editing the file.
